import React from 'react';

export const Disclaimer = () => {
  return (
    <div className="min-h-screen bg-gray-50 py-12">
      <div className="max-w-4xl mx-auto px-4">
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-8">
          <h1 className="text-3xl font-bold text-gray-800 mb-6">Disclaimer</h1>
          
          <div className="space-y-6 text-gray-700">
            <section>
              <h2 className="text-xl font-semibold text-gray-800 mb-3">General Information</h2>
              <p>
                The QR codes generated by this service are provided "as is" without any warranties, 
                expressed or implied. We do not guarantee the accuracy, reliability, or completeness 
                of any QR code generated through our platform.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-800 mb-3">User Responsibility</h2>
              <p>
                Users are solely responsible for the content they encode in QR codes. Please ensure 
                that your use of generated QR codes complies with all applicable laws and regulations. 
                Do not generate QR codes for malicious, illegal, or harmful content.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-800 mb-3">Data Privacy</h2>
              <p>
                We do not store the content of the QR codes you generate. However, we may collect 
                anonymous usage statistics to improve our service. Your generated QR codes are 
                processed in real-time and not permanently stored on our servers.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-800 mb-3">Third-Party Content</h2>
              <p>
                QR codes may link to third-party websites or services. We are not responsible for 
                the content, privacy policies, or practices of any third-party sites or services.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-800 mb-3">Limitation of Liability</h2>
              <p>
                In no event shall QR Generator be liable for any direct, indirect, incidental, 
                special, or consequential damages arising out of or in connection with the use 
                or inability to use our service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-800 mb-3">Service Availability</h2>
              <p>
                We strive to maintain 24/7 service availability but do not guarantee uninterrupted 
                access. We reserve the right to modify or discontinue our service at any time 
                without notice.
              </p>
            </section>

            <div className="bg-yellow-50 border border-yellow-200 rounded-md p-4 mt-8">
              <p className="text-yellow-800 text-sm">
                <strong>Note:</strong> This disclaimer may be updated from time to time. 
                Please check this page periodically for changes.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};